### ISSUE TITLE
AssetPack name is taken from bundlePath

### ISSUE THREAD

**Issue by MichalDolezalAG** [google/play-unity-plugins#143] opened 2021-09-04 17:10 UTC
We are using unity addressables that generate bundle files with .bundle extension. So when we tried to add assetPack with that extension, we got error InvalidBundleName.
So we found a workaround, where we directly add to AssetPacks in AssetPackConfig:
```
config.AssetPacks.Add(addressableGroupBase.BundleName, new AssetPack()
				{
					AssetBundleFilePath = addressableGroupBase.FilePath,
					DeliveryMode = addressableGroupBase.InstallTimeDelivery ? AssetPackDeliveryMode.InstallTime : AssetPackDeliveryMode.OnDemand
				});
```
This worked just fine until we updated AssetDelivery from 1.4.0 to 1.5.0. Then, after running BundleTool, Unity builds entire game and at the very end it gets exception InvalidBundleName - asset pack name "PATH_TO_BUNDLE" is invalid.

**Comment by jamcohen** [comment] 2021-09-08 00:25
Hi @MichalDolezalAG,

Thank you for reporting this!

I found that the root cause is a bug in [SerializationHelper.Deserialize()](https://github.com/google/play-unity-plugins/blob/e6134882f68c7d04b322d82dbe778545dfefab12/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/Config/SerializationHelper.cs#L140) where we use a name derived from the path instead of the actual name.

This only became an issue in 1.5.0 because we added a [DeepCopy](https://github.com/google/play-unity-plugins/blob/e6134882f68c7d04b322d82dbe778545dfefab12/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/Config/SerializationHelper.cs#L39) to [CreateBundleAsync()](https://github.com/google/play-unity-plugins/blob/71d7226e4c485ae2b90191f9175b7c18572f9e8a/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/BuildTools/AppBundleBuilder.cs#L332). Since we implemented DeepCopy using serialization and deserialization, it started to trigger the bug.

I'll include a fix for this in the next release.

In the meantime you can replace [this line](https://github.com/google/play-unity-plugins/blob/e6134882f68c7d04b322d82dbe778545dfefab12/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/Config/SerializationHelper.cs#L140) with the following:
```
assetPackConfig.AssetPacks.Add(multiTargetingAssetBundle.name, new AssetPack()
{
    AssetBundleFilePath = assetBundles[0].path,
    DeliveryMode = multiTargetingAssetBundle.DeliveryMode
});
```

Let me know if that works.

Best,
Jake Cohen

**Comment by MichalDolezalAG** [comment] 2021-09-08 11:17
Thank you @jamcohen for quick response.

I tried suggested fix and it worked!

**Closed** 2022-02-02 15:41 UTC
