### ISSUE TITLE
Unable to load asset packs in universal.apk

### ISSUE THREAD

**Issue by jeffason** [google/play-unity-plugins#23] opened 2020-06-02 20:10 UTC
We are building an AAB with many of Unity's addressables asset bundles put into asset packs.  The AAB works fine deployed to the Play Store and installed from an .apks built with `--mode default`

However, when we attempt to run the game from an .apks built with `--mode universal` we get a java exception when we call `PlayAssetDelivery.RetrieveAssetBundleAsync()`

Here are the java exception details:
![image](https://user-images.githubusercontent.com/3349419/83564881-0fedde00-a4e3-11ea-8157-c44ee1c5642f.png)

In this case our game hangs because our PlayAssetBundleRequest.Completed event never fires.

**Comment by jamcohen** [comment] 2020-06-02 21:56
Thanks for raising this issue.
Are you using upfront asset packs, or on-demand/fast-follow packs?

**Comment by jeffason** [comment] 2020-06-03 15:08
All my tests were with `install-time` asset packs

**Comment by jamcohen** [comment] 2020-06-04 00:21
It looks like bundletool strips out all asset packs when creating apks with `--mode=universal`, so the `install-time` packs that the app is expecting to be installed alongside the app are missing.

I'll reach out to the bundletool team and see what the expected behavior should be.

**Comment by jeffason** [comment] 2020-06-04 15:41
@jamcohen which version of bundletool are you using for your tests? I am using `0.14.0` and when I extract my universal.apk, I see the asset packs in my assets dir (as expected)

![image](https://user-images.githubusercontent.com/3349419/83778124-e605fa00-a64f-11ea-8d02-e14759024a64.png)

**Comment by jamcohen** [comment] 2020-06-04 17:47
Ah, you are correct. I saw that there was no asset-slices folder in the universal .apks file and incorrectly assumed they were stripped out. It makes sense that they're included in the .apk itself.

In that case, my guess is that the underlying java library, [Play Core](https://developer.android.com/guide/playcore),  assumes that the asset packs are installed in /file/assetpacks/ and neglects to handle the case when they're present in the apk. I'll reach out to the Play Core team and keep you updated.

**Comment by jeffason** [comment] 2020-06-04 18:19
awesome thanks!

**Comment by jeffason** [comment] 2020-06-12 16:07
Hey @jamcohen , just checking in if you have any update and if the playcore team could reproduce the issue?  Being able to leverage this feature would provide great benefits!

**Comment by jamcohen** [comment] 2020-06-13 01:15
Hey Jeff, apologies for not providing an update sooner. We were able to reproduce the issue and are working towards a fix.

**Comment by jamcohen** [comment] 2020-06-15 22:31
We just fixed this issue in [Play Core](https://developer.android.com/guide/playcore). That fix will be present in the next version of Play Core which will be included in the next release of the com.google.play.core Unity package. I'll close out this issue once that's released.

Thanks for reporting this!

**Comment by jamcohen** [comment] 2020-08-05 01:52
The fix was included in our 1.2 release: https://github.com/google/play-unity-plugins/releases/tag/v1.2.0

**Closed by jamcohen** 2020-08-05 01:52 UTC
